using System;
using System.Collections.Generic;
using System.Text;

namespace DddModelGen
{
    internal static class Constants
    {
        public const string NamespaceName = "DddModels";

        public const string MainAttributeClassName = "StronglyTypedValueAttribute";

        public const string EfConverterAttributeClassName = "StronglyTypedValueEfConverterAttribute";

        public const string SharedCodeHeader = """
// <auto-generated>
// THIS (.cs) FILE IS GENERATED. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
""";

    }
}
